nginx:
    image: 'nginx:1.13.1'
    ports:
        - '80:80'
    links:
        - phpfpm
    volumes:
        - ./logs:/var/logs/nginx
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./public:/myapps
phpfpm:
    image: 'php:7.1.6-fpm-alpine'
    ports:
        - '9000:9000'
    volumes:
        - ./public:/myapps
    links:
        - mysql
mysql:
    image: 'mariadb'
    ports:
        - '3306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=hakase-labs123

